Update mailbox.c
Compilation return error:
mailbox.c:(.text+0xc54): undefined reference to `makedev'

makedev() is actually a macro and we need to include the correct header for it.